---
- name: Install common dependencies
  become_user: root
  become: yes
  ansible.builtin.apt:
    pkg:
      - build-essential
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3.10-dev
      - python3.10-distutils
      - python3.10-venv
      - software-properties-common
    state: present
    force: yes
    update_cache: true
